export const ActionTypes = {
  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',

  FETCH_STUDENT_INFO_REQUEST: 'FETCH_STUDENT_INFO_REQUEST',
  FETCH_STUDENT_INFO_SUCCESS: 'FETCH_STUDENT_INFO_SUCCESS',
  FETCH_STUDENT_INFO_FAILURE: 'FETCH_STUDENT_INFO_FAILURE',

  FETCH_MOVIE_RECENT_REQUEST: 'FETCH_MOVIE_RECENT_REQUEST',
  FETCH_MOVIE_RECENT_SUCCESS: 'FETCH_MOVIE_RECENT_SUCCESS',
  FETCH_MOVIE_RECENT_FAILURE: 'FETCH_MOVIE_RECENT_FAILURE',

  FETCH_MOVIE_TOP_REQUEST: 'FETCH_MOVIE_TOP_REQUEST',
  FETCH_MOVIE_TOP_SUCCESS: 'FETCH_MOVIE_TOP_SUCCESS',
  FETCH_MOVIE_TOP_FAILURE: 'FETCH_MOVIE_TOP_FAILURE',

  FETCH_MOVIE_VIEWED_REQUEST: 'FETCH_MOVIE_VIEWED_REQUEST',
  FETCH_MOVIE_VIEWED_SUCCESS: 'FETCH_MOVIE_VIEWED_SUCCESS',
  FETCH_MOVIE_VIEWED_FAILURE: 'FETCH_MOVIE_VIEWED_FAILURE',

  FETCH_VIEWED_MOVIE_LIST_REQUEST: 'FETCH_VIEWED_MOVIE_LIST_REQUEST',
  FETCH_VIEWED_MOVIE_LIST_SUCCESS: 'FETCH_VIEWED_MOVIE_LIST_SUCCESS',
  FETCH_VIEWED_MOVIE_LIST_FAILURE: 'FETCH_VIEWED_MOVIE_LIST_FAILURE',

  FETCH_STAR_MOVIE_LIST_REQUEST: 'FETCH_STAR_MOVIE_LIST_REQUEST',
  FETCH_STAR_MOVIE_LIST_SUCCESS: 'FETCH_STAR_MOVIE_LIST_SUCCESS',
  FETCH_STAR_MOVIE_LIST_FAILURE: 'FETCH_STAR_MOVIE_LIST_FAILURE',

  SYNC_MOVIE_RECENT_REQUEST: 'SYNC_MOVIE_RECENT_REQUEST',
  SYNC_MOVIE_RECENT_SUCCESS: 'SYNC_MOVIE_RECENT_SUCCESS',
  SYNC_MOVIE_RECENT_FAILURE: 'SYNC_MOVIE_RECENT_FAILURE',

  SYNC_MOVIE_TOP_REQUEST: 'SYNC_MOVIE_TOP_REQUEST',
  SYNC_MOVIE_TOP_SUCCESS: 'SYNC_MOVIE_TOP_SUCCESS',
  SYNC_MOVIE_TOP_FAILURE: 'SYNC_MOVIE_TOP_FAILURE',
};
