export const ActionTypes = {
  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',

  FETCH_STUDENT_INFO_REQUEST: 'FETCH_STUDENT_INFO_REQUEST',
  FETCH_STUDENT_INFO_SUCCESS: 'FETCH_STUDENT_INFO_SUCCESS',
  FETCH_STUDENT_INFO_FAILURE: 'FETCH_STUDENT_INFO_FAILURE',

  FETCH_MOVIE_RECENT_REQUEST: 'FETCH_MOVIE_RECENT_REQUEST',
  FETCH_MOVIE_RECENT_SUCCESS: 'FETCH_MOVIE_RECENT_SUCCESS',
  FETCH_MOVIE_RECENT_FAILURE: 'FETCH_MOVIE_RECENT_FAILURE',

  FETCH_MOVIE_TOP_REQUEST: 'FETCH_MOVIE_TOP_REQUEST',
  FETCH_MOVIE_TOP_SUCCESS: 'FETCH_MOVIE_TOP_SUCCESS',
  FETCH_MOVIE_TOP_FAILURE: 'FETCH_MOVIE_TOP_FAILURE',

  FETCH_MOVIE_VIEWED_REQUEST: 'FETCH_MOVIE_VIEWED_REQUEST',
  FETCH_MOVIE_VIEWED_SUCCESS: 'FETCH_MOVIE_VIEWED_SUCCESS',
  FETCH_MOVIE_VIEWED_FAILURE: 'FETCH_MOVIE_VIEWED_FAILURE',

};