export const ActionTypes = {
  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',

  FETCH_STUDENT_INFO_REQUEST: 'FETCH_STUDENT_INFO_REQUEST',
  FETCH_STUDENT_INFO_SUCCESS: 'FETCH_STUDENT_INFO_SUCCESS',
  FETCH_STUDENT_INFO_FAILURE: 'FETCH_STUDENT_INFO_FAILURE',
};